## 2. Load the PrimeKG dataset

Mount Google Drive, point to the PrimeKG source folder, and load `kg.csv` into `raw_df`. The inspection steps that follow are mainly there to confirm the file loaded correctly.

In [ ]:
# Mount Google Drive
drive.mount("/content/drive")

# Set the dataset path
DATA_DIR = Path("/content/drive/MyDrive/DS5500 - Capstone Project/Datasets/source")

%cd {DATA_DIR}

KG_FILE = DATA_DIR / "kg.csv"

if not KG_FILE.exists():
    raise FileNotFoundError(
        f"kg.csv not found at {KG_FILE}.\n"
        "Download PrimeKG from: https://github.com/mims-harvard/PrimeKG"
    )

# Load the raw CSV
print("Loading kg.csv - Consists of ~8M records")
raw_df = pd.read_csv(KG_FILE, low_memory=False)
print("Done.\n")

# Basic inspection
print("=" * 55)
print("  DATASET SUMMARY")
print("=" * 55)
print(f"  Rows    : {len(raw_df):,}")
print(f"  Columns : {raw_df.shape[1]}")
print(f"  Memory  : {raw_df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")
print()
print("  Column names:")
for col in raw_df.columns:
    print(f"    {col}")
print("=" * 55)

# Check missing values and duplicates
missing = raw_df.isnull().sum()
if missing.any():
    print("\n  Missing values per column:")
    print(missing[missing > 0].to_string())
else:
    print("\n  No missing values found.")

n_dupes = raw_df.duplicated().sum()
print(f"\n  Duplicate rows : {n_dupes:,}")

# Preview the data
print("\n  First 5 rows:")
display(raw_df.head())

print("\n  Column dtypes:")
display(raw_df.dtypes.to_frame("dtype"))

print("\n  Original Dataset:")
raw_df

Mounted at /content/drive
/content/drive/MyDrive/DS5500 - Capstone Project/Datasets/source
Loading kg.csv - Consists of ~8M records
Done.

=======================================================
  DATASET SUMMARY
=======================================================
  Rows    : 8,100,498
  Columns : 12
  Memory  : 4678.7 MB

  Column names:
    relation
    display_relation
    x_index
    x_id
    x_type
    x_name
    x_source
    y_index
    y_id
    y_type
    y_name
    y_source
=======================================================

  No missing values found.

  Duplicate rows : 0

  First 5 rows:

          relation display_relation  x_index  x_id        x_type  x_name x_source  y_index   y_id        y_type  y_name y_source
0  protein_protein              ppi        0  9796  gene/protein  PHYHIP     NCBI     8889  56992  gene/protein   KIF15     NCBI
1  protein_protein              ppi        1  7918  gene/protein  GPANK1     NCBI     2798   9240  gene/protein   PNMA1     NCBI
2  protein_protein              ppi        2  8233  gene/protein   ZRSR2     NCBI     5646  23548  gene/protein   TTC33     NCBI
3  protein_protein              ppi        3  4899  gene/protein    NRF1     NCBI    11592  11253  gene/protein  MAN1B1     NCBI
4  protein_protein              ppi        4  5297  gene/protein   PI4KA     NCBI     2122   8601  gene/protein   RGS20     NCBI

  Column dtypes:

                   dtype
relation          object
display_relation  object
x_index            int64
x_id              object
x_type            object
x_name            object
x_source          object
y_index            int64
y_id              object
y_type            object
y_name            object
y_source          object

  Original Dataset:

                       relation   display_relation  x_index  x_id        x_type                   x_name x_source  y_index       y_id        y_type  y_name y_source
0               protein_protein                ppi        0  9796  gene/protein                   PHYHIP     NCBI     8889      56992  gene/protein   KIF15     NCBI
1               protein_protein                ppi        1  7918  gene/protein                   GPANK1     NCBI     2798       9240  gene/protein   PNMA1     NCBI
2               protein_protein                ppi        2  8233  gene/protein                    ZRSR2     NCBI     5646      23548  gene/protein   TTC33     NCBI
3               protein_protein                ppi        3  4899  gene/protein                     NRF1     NCBI    11592      11253  gene/protein  MAN1B1     NCBI
4               protein_protein                ppi        4  5297  gene/protein                    PI4KA     NCBI     2122       8601  gene/protein   RGS20     NCBI
...                         ...                ...      ...   ...           ...                      ...      ...      ...        ...           ...     ...      ...
8100493  anatomy_protein_absent  expression absent    66747  4720       anatomy        cerebellar vermis   UBERON     5259        140  gene/protein  ADORA3     NCBI
8100494  anatomy_protein_absent  expression absent    63824  1377       anatomy       quadriceps femoris   UBERON    58254  105378952  gene/protein   KLF18     NCBI
8100495  anatomy_protein_absent  expression absent    63826  1379       anatomy         vastus lateralis   UBERON    58254  105378952  gene/protein   KLF18     NCBI
8100496  anatomy_protein_absent  expression absent    64523  2084       anatomy     heart left ventricle   UBERON    58254  105378952  gene/protein   KLF18     NCBI
8100497  anatomy_protein_absent  expression absent    67302  5384       anatomy  nasal cavity epithelium   UBERON    58254  105378952  gene/protein   KLF18     NCBI

[8100498 rows x 12 columns]